name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.8.0'  # Adjust .NET version as needed

      - name: Build and Test
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test --no-restore --verbosity normal
