name: Deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Deploy to IIS
        uses: appleboy/rsync-action@v2
        with:
          args: -r -e 'ssh -p ${{ secrets.SSH_PORT }}' --delete-after
          source: build/
          host: ${{ secrets.IIS_SERVER }}
          user: ${{ secrets.IIS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          dest: "/your/iis/wwwroot/path"
