name: SonarCloud-Metrics

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Change this to your main branch

jobs:
  sonarCloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sonar Clound Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=mufaddalsr
            -Dsonar.projectKey=Mufaddalsr_Laundry-Management-MaxLaundry
        ##   -Dsonar.python.coverage.reportPaths=coverage.xml
